# Generated by Django 4.0.4 on 2022-09-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='create_date',
            new_name='date',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
